jpmorganchase/nbcelltests

Makefile
jupyterlab_celltests/extension.py
jupyterlab_celltests/lint.py
jupyterlab_celltests/tests.py
tests/test_extension.py
tests/test_init.py
tests/test_lint.py
tests/test_tests.py

fixes #13 
partial fix for #21

Allow for overriding lint/test rules from jupyter config or command line

---

.bumpversion.cfg
jupyterlab_celltests/_version.py
package.json

Release 0.1.1 #39

---

src/run.ts

Fix detection of test/lint cancellation.

---

azure-pipelines.yml

Only upload packages for "release-style" tags.

Only upload packages on 'release style' tag.

---

Makefile
setup.py
tests/test_all.py
tests/test_extension.py
tests/test_init.py
tests/test_lint.py
tests/test_shared.py
tests/test_tests.py

And fix the faults found (to a reasonable extent).
Should have no impact; couple of unused names but mainly formatting.

Add tests and setup.py to lint check

---

MANIFEST.in
setup.py

Update packaging of tests after recent reorg.

---

nbcelltests/test.py
nbcelltests/tests/test_test.py
setup.py

Fixes #130 
Also adds some docstrings to various run fns (work towards #122).

Test runWithHTMLReturn()

---

Makefile
nbcelltests/__init__.py
nbcelltests/extension.py
nbcelltests/tests/test_extension.py
nbcelltests/tests/test_init.py

Fixes #138 
Copy what nbdime does.
To do:

Allow server extension to be referred to as nbcelltests 

---

nbcelltests/shared.py
nbcelltests/tests/basic.ipynb

Don't count empty lines.

---

.bumpversion.cfg
js/package.json
nbcelltests/_version.py

Let's see what we broke this time :)

Bump version: 0, 2, 0, 'alpha', 1 → 0, 2, 0, 'alpha', 2

---

.bumpversion.cfg
js/package.json
nbcelltests/_version.py

Bump version: 0, 2, 0, 'alpha', 2 → 0, 2, 0, 'final', 0

---

CONTRIBUTING.md
nbcelltests/tests/_input_cell_multiline_string.ipynb
nbcelltests/tests/_input_cell_newline_string.ipynb
nbcelltests/tests/_input_test_injection_comment.ipynb
nbcelltests/tests/_input_test_multiline_string.ipynb
nbcelltests/tests/_input_test_newline_string.ipynb
nbcelltests/tests/test_test.py

Tests for #162, all currently marked as known failures.
Also minor fixups for contributor guide.
It's very likely I could fix up the code to make these pass, but I think it would probably be better to replace that code entirely (I'm referring to the internal building up of code in a string).

Some input handling checks

---

MANIFEST.in
README.md
nbcelltests/tests/test_test.py

* Typos in README
* Exclude some files that might (?) otherwise be included in dists (if not made from a clean repo?) (I copied this list from another of our projects...any chance this kind of config could be shared?)
* Fixed indentation mistake in tests (would just have been resulting in a more confusing error message in case of failure).

Miscellaneous fixes

---

nbcelltests/tests/_no_code_cells.ipynb
nbcelltests/tests/test_test.py
nbcelltests/tests_vendored.py

Don't fall over notebooks with no code cells.

---

nbcelltests/test.py
nbcelltests/tests/_kernel_check.ipynb
nbcelltests/tests/_kernel_check1.ipynb
nbcelltests/tests/test_test.py
nbcelltests/tests_vendored.py

Allow to switch kernels

---

nbcelltests/tests/_kernel_cwd.ipynb
nbcelltests/tests/test_test.py
nbcelltests/tests_vendored.py

cwd like it's jupyter

---

.bumpversion.cfg
MANIFEST.in
js/package.json
nbcelltests/_version.py

And bump version for new package build.

Explicitly include pyproject.toml in MANIFEST.in

---

.bumpversion.cfg
MANIFEST.in
js/package.json
nbcelltests/_version.py

Sorry, typo in the last PR! :(

Fixed missing command.

---

CONTRIBUTING.md

Add notes in the setup instructions to help first-time users install correct versions of required packages.

Clarify setup steps in CONTRIBUTING.md

---

nbcelltests/shared.py
nbcelltests/tests/_lint_disable_empty_cell.ipynb
nbcelltests/tests/test_shared.py

Fixes #194 
(includes more of the bad and lazy copy/paste complained about in #150)

Find noqa comments in empty ast code cells.

---

CONTRIBUTING.md

Helps those who have not used yarn before.

Clarify yarn test directory
