- jupyterlab_celltests/tests.py
- requirements.txt
Fixes  #29.
Since the outer python process is not running in a pytest context, we cannot use inprocess execution to get detailed reports. So instead we serialize out the test reports via JSON so that we can read them in our main process.
TODO: Pre-process the report dicts some to make them more easily useable (since we cannot deserialize back to the original object type, as we are not in a pytest context).
> Add way to run with detail report objects

- jupyterlab_celltests/tests.py
Use to only collect tests, e.g. to introspect which tests exists.
Usage example:
```python
In[]:
from jupyterlab_celltests.tests import runWithReport
report = runWithReport('Untitled.ipynb', collect_only=True)
for r in report['collected_items']:
print(r['nodeid'])
Out[]:
Untitled.py::TestExtension::test_cell0
Untitled.py::TestExtension::test_cell1
Untitled.py::TestExtension::test_cell2
Untitled.py::TestExtension::test_cell3
Untitled.py::TestExtension::test_cell4
Untitled.py::TestExtension::test_cell_coverage
Untitled.py::TestExtension::test_cells_per_notebook
Untitled.py::TestExtension::test_class_definition_count
Untitled.py::TestExtension::test_function_definition_count
Untitled.py::TestExtension::test_lines_per_cell_0
Untitled.py::TestExtension::test_lines_per_cell_1 …
```
> Add collect_only flag to runWithReport

- jupyterlab_celltests/lint.py
Currently, the generated py script could be empty at the time of lint checking (so lint would always pass) because the file hasn't been written to disk:
`test3` and `好` are both undefined names - lint should fail. Calling `close()` on the file before reading it from another process should fix this.
(This might vary by platform. Here I'm on linux. I think on Win the file would always need to be closed anyway or there'll be an error - not sure.)
Currently (assuming the above issue is fixed), if there is unicode in the notebook that appears as lint, the celltests lint check will crash:
```
[E 20:52:25.061 LabApp] Uncaught exception POST /celltests/lint/run (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/celltests/lint/run', version='HTTP/1.1', …
```
> WIP: Clean up how linter gets called.

- .travis.yml
- CONTRIBUTING.md
- README.md
- jupyterlab_celltests/lint.py
- requirements.txt
- setup.py
* Added missing dev step (jupyter serverextension enable).
* flake8, pytest, and pytest-html appear to be end-user run dependencies (not just dev dependencies).
* Added missing dev dependency (mock).
* Removed apparently unused dev dependency (pylint).
* Added note about lint checking py2 notebooks.
* Made the minimum python version clearer. 
* celltests was python 3.5+ only (despite what its packaging says) until #42 was merged, which made it 3.7+ only. 
* This PR makes the minimum python be 3.6, since it was easy to do. 
* If it's also not ok to drop 3.5 support yet, I could work around that too (subprocess.run () didn't get the encoding parameter until 3.6). 
* Things that made celltests be incompatible with py2 and require 3.5+ include that subprocess.run() didn't appear til 3.5, …
> Clean up packaging

- src/widget.ts
* Fix metadata saving - actually set celltests metadata after editing (was previously set to undefined).
* Fix metadata loading - actually load metadata when opening new notebook, etc.
* Update metadata if number is changed (not just on checkbox enable/disable).
* Make default values consistent with ranges.
* Store numbers as numbers in metadata, rather than strings (and disallow strings).
* Correctly enable/disable entries if metadata key is present/absent.
* Allow to enforce zero function/class definitions (could previously only enforce a max of one).
* Fix setting of zero (falsely) minimums (could previously be set below zero without complaint).
* Clear value when unchecking an entry, and reset to default when checking an entry.
Still to do:
* ~~Reduce some of the duplication...~~ …
> Fix notebook-level celltests metadata editing

- jupyterlab_celltests/extension.py
- jupyterlab_celltests/tests.py
* Fixes for win paths.
* Explicitly specify utf8 when opening files (for platforms such as Win where default encoding is likely to be something else).
> Fixups for running on Windows

- jupyterlab_celltests/shared.py
- tests/basic.ipynb
- tests/more.ipynb
- tests/test_shared.py
Currently the class and function definition counting is based on a regex, which can't work in general. Added some basic tests to show where it fails (e.g. things in comments/docstrings, things like `if reclass(x):`, etc), and replaced with ast parsing.
> Fix counting of class and function definitions

- jupyterlab_celltests/lint.py
- tests/test_lint.py
* Add tests of lint lines per cell.
* FIx lint_lines_per_cell to handle the default (-1, meaning "don't check", currently always fails). Also simplify.
* Add tests of lint cells per notebook (initially failing one case - 0).
* Fix lint cells per notebook to handle 0 (could be used to disallow code cells). Also simplify.
* Add tests of lint function definitions per notebook (initiall failing one case - 0).
* Fix lint functions definitions per notebook to handle 0 (could be used to disallow fns).
* Simplify lint function definitions per notebook.
* Add test of class definitions per notebook (initially failing one case - 0).
* Fix lint class definitions per notebook to handle 0.
* Simplify lint class definitions per notebook function.
* Add tests for lint cell coverage.
* Simplify lint cell …
> Start to clean up lint checks (fixing edge cases), and add tests.

- jupyterlab_celltests/lint.py
Adds `(max=n; actual=m)` to the message:
```
FAILED: Checking lines in cell (max=1; actual=3) (Cell 1)
PASSED: Checking lines in cell (max=1; actual=1) (Cell 2)
PASSED: Checking lines in cell (max=1; actual=1) (Cell 3)
PASSED: Checking lines in cell (max=1; actual=1) (Cell 4)
PASSED: Checking lines in cell (max=1; actual=1) (Cell 5)
FAILED: Checking cells per notebook (max=3; actual=5) (Notebook)
PASSED: Checking functions per notebook (max=10; actual=1) (Notebook)
PASSED: Checking classes per notebook (max=10; actual=0) (Notebook)
PASSED: Checking cell test coverage (min=50; actual=60.0) (Notebook)
FAILED: Checking lint:
/tmp/tmpv_7t581g.py:11:1: E302 expected 2 blank lines, found 0
/tmp/tmpv_7t581g.py:11:1: E704 multiple statements on one line (def)
/tmp/tmpv_7t581g.py:33:1: F821 …
```
> More informative lint messages

- jupyterlab_celltests/lint.py
- jupyterlab_celltests/shared.py
- tests/test_lint.py
Simplify the lint functions and add tests of lint.run(); no change in behavior.
The tests of lint.run() pass before and after this PR's changes.
To do:
> Simplify/clarify the lint functions (should be no behavior change).

- jupyterlab_celltests/define.py
- jupyterlab_celltests/lint.py
- jupyterlab_celltests/shared.py
- tests/test_lint.py
Currently, when you call `lint.run()` programmatically, you can pass a dictionary of rules - e.g. `lint.run(rules={'lines_per_cell':5, 'cells_per_notebook':5}`). This PR adds `kernelspec_requirements` as another lint rule, e.g. `lint.run({'lines_per_cell':5, 'cells_per_notebook':5, 'kernelspec_requirements': {'name':'python3'})`.
Should it be more flexible (e.g. to allow multiple possible kernel names, or a regex on kernel names, etc)?
> Add ability to check kernelspec

- jupyterlab_celltests/shared.py
- requirements.txt
- tests/more.ipynb
- tests/test_lint.py
- tests/test_shared.py
Currently, celltests will report a syntaxerror for any notebook containing magics.
This PR allows celltests to handle magics without any problems by using nbconvert to first convert to python.
For instance, before this PR, lint checking this would result in a syntax error, but it's now fine:
```
%matplotlib inline
x = 1
```
However, counts will not always be accurate. Using nbconvert alone results in: 
1. line magics being able to mask code:
```
%time def f(): pass
```
`f` will not be counted as a function definition.
2. cell magics masking code:
```
%%capture
def f(): pass
```
`f` will not be counted as a function definition.
As far as I know, this is a limitation of nbconvert, and affects various projects in various ways. However, both those two limitations can be overcome with more …
> Add basic magics handling (for counting cell, function definitions).

- jupyterlab_celltests/define.py
- jupyterlab_celltests/lint.py
- jupyterlab_celltests/shared.py
- tests/magics.ipynb
- tests/test_lint.py
- tests/test_shared.py
Allow optional specification of either a whitelist of acceptable magics, or a blacklist of unacceptable magics (but not both). 
Specifying a whitelist restricts to only those entries (an empty whitelist denying all magics), while specifying a blacklist rejects any of those entries.
The existing default behavior (any magic's acceptable) is unchanged.
Currently, when you call `lint.run()` programmatically, you can pass a dictionary of rules - e.g.
```
>>> import jupyterlab_celltests.lint as lint
>>> lint.run("tests/more.ipynb",rules={'cells_per_notebook':20})
([PASSED: Checking cells per notebook (max=20; actual=6) (Notebook)], True)
```
This PR adds `magics_whitelist` or `magics_blacklist` as an optional lint rule, e.g. 
```
>>> import jupyterlab_celltests.lint as lint
>>> …
```
> Support for magics whitelist/blacklist

- Makefile
- azure-pipelines.yml
- setup.py
* setup.py: Don't prevent people from installing on python 2.7 (even though not all of celltests will work on python 2.7)
* setup.py: fix long description content type (display md on pypi).
* Makefile: Split up package creation and upload.
* Azure pipeline: Build python packages and store as azure artifacts.
Packages get uploaded to a feed from the linux build:
That's available as https://pkgs.dev.azure.com/tpaine154/jupyter/_packaging/python-packages/pypi/simple/
I was able to install the azure artifact into a clean environment:
```
$ pip install --index-url=https://pkgs.dev.azure.com/tpaine154/jupyter/_packaging/python-packages/pypi/simple/ jupyterlab_celltests --extra-index-url=https://pypi.org/simple
Looking in indexes: https://pkgs.dev.azure.com/tpaine154/jupyter/_packaging/python-pac …
```
> Miscellaneous packaging improvements (including python packages stored as azure artifacts)

- .bumpversion.cfg
- CONTRIBUTING.md
- azure-pipelines.yml
- setup.py
* Add package.json to files managed by bumpversion.
* Have bumpversion do the git tagging (requires [bump2version](https://pypi.org/project/bump2version/))
* npm package creation and upload to feed (on tag, as was done for python)
* Proposal for how to do releases (see CONTRIBUTING.md)
Questions:
Now it commits, tags, and updates package.json...
```
$ git tag -l
[...]
v0.1.2
$ bump2version patch
$ head .bumpversion.cfg package.json 
==> .bumpversion.cfg <==
[bumpversion]
current_version = 0, 1, 3, 'alpha', 0
commit = True
tag = True
tag_name = v{new_major}.{new_minor}.{new_patch}{new_release}{new_build}
parse = (?P<major>\d+)\,\ (?P<minor>\d+)\,\ (?P<patch>\d+)\,\ \'(?P<release>\S+)\'\,\ (?P<build>\d+)
serialize = 
{major}, {minor}, {patch}, '{release}', {build}
[bumpversion:part:release] …
```
> Improvements to release procedure

- CONTRIBUTING.md
- Makefile
How to download and install labextension from azure. No idea how to find the direct download link on azure. Otherwise, could just `jupyter labextension install https://azure-link/jupyterlab_celltests-0.1.3-alpha.0.tgz` or whatever.
Also: add missing docs to Makefile.
> Instructions for installing labextension from azure

- nbcelltests/lint.py
- nbcelltests/tests/test_lint.py
Bug fix: "class definitions" lint check was returning the "function definition" lint type.
Bug would affect anyone who was:
* displaying the lint type ("cosmetic")
* conditioning something on the lint type, with different conditions for function and class definition counts.
This PR also adds tests that lint type is as expected.
> Bug fix: return correct lint type for class definition checks

- nbcelltests/lint.py
Minor: presumably the remove could have failed if the file was not successfully created in the first place.
(https://bugs.python.org/issue14243 for example of why I keep not being able to remember how to use named temporary file properly on windows)
> Clarify some temporary file handling

- README.md
Currently, it's showing coverage for the most recent build.
(Don't know how to fix the link to lead somewhere more useful, though.)
> Ensure coverage badge shows stats from master

- .azure/pipelines.yml
- .azure/template.yml
- Makefile
- nbcelltests/tests/_cell_error.ipynb
- nbcelltests/tests/_cumulative_run.ipynb
- nbcelltests/tests/_test_error.ipynb
- nbcelltests/tests/_test_fail.ipynb
- nbcelltests/tests/test_test.py
- nbcelltests/tests_vendored.py
- setup.py
> Test and fix the notebook tester

- nbcelltests/tests_vendored.py
Note: in its current form, depends on #90 
While I think it might be possible to take an entirely different approach to testing notebooks, at least moving most of the code in `tests_vendored` out of a string will:
* make it easier to work with the code
* allow the code to be tested and linted
* prevent each generated test script having the "run test" machinery vendored in (e.g. what if there's a bug in the run tests code...you'd have to update every generated test script...)
The downside is that the generated test script depends on `nbcelltests.tests_vendored`. But that doesn't seem unreasonable to me. What do you think?
Or if there are other downsides, please let me know!
This PR doesn't represent how I think things should be organized, but I first want to find out if there are any …
> Reduce amount of code stored in string in tests_vendored: import it instead

- nbcelltests/shared.py
- nbcelltests/test.py
- nbcelltests/tests/_cell_counting.ipynb
- nbcelltests/tests/_non_code_cell.ipynb
- nbcelltests/tests/_skips.ipynb
- nbcelltests/tests/test_test.py
- nbcelltests/tests_vendored.py
Fixes #97 and fixes #99. Same tests as in #111, just updated for 1-based counting.
1. Test methods are only generated for code cells. If a non-code cell contains a test in its metadata, it's an error at generation time. Only code cells will be included in "cell coverage" calculation.
2. Test methods are named like `test_code_cell_n` (so you know it's only code cells), where `n` is the 1-based code cell number - i.e. they are numbered like execution count (if run from scratch).
Example: If there are 3 cells, and the 2nd cell is markdown, then there'll just be two test methods, `test_code_cell_1` and `test_code_cell_2`.
3. Code cells that are empty or do not have a test still generate a test method, but decorated with `@skip(reason)` (where `reason` is `"empty code cell"` or `"cell has no …
> Fix code/test correspondence; explicitly skip test empty cells/tests.

- nbcelltests/shared.py
- nbcelltests/test.py
- nbcelltests/tests/coverage.ipynb
- nbcelltests/tests/test_lint.py
- nbcelltests/tests/test_shared.py
- nbcelltests/tests/test_test.py
Tests: fixes #118
Lint: closes #83
Notes:
* Fixed `shared.get_coverage()`, which was completely broken, and was apparently unused (definitely untested).
* Reduced number of times "is cell tested?" is defined.
Question: is there any point offering an option to count the old way, i.e. to count empty cells if preferred. In #83 I speculated that someone might want to limit the number of empty cells (e.g. so their notebooks look nice!), but on reflection I agree with @vidartf that it's not necessary (i.e. I vote "no").
> Don't count empty code cells for lint's "max cells per nb" or for coverage

- nbcelltests/test.py
- nbcelltests/tests/_test_fail.ipynb
- nbcelltests/tests/test_test.py
- nbcelltests/tests_vendored.py
Fixes #105 
Generated test script now contains cell+test source strings (as dict,  cell number: contents) separately from test methods. Rather than each test method containing all previous cells+tests, each test method just contains own cell+test, and test script tracks execution so that preceding cells+tests are run if necessary (i.e. if they haven't already run).
To do:
> Track cell+test execution

- .azure/template.yml
> Add python 3.6 and 3.8 to azure build matrix.

- nbcelltests/test.py
Leaves only coverage test + cell tests being written out into the generated test file. Was mistakenly missed from an earlier PR which removed the rest (cell count, etc).
> Clean up: remove code accidentally not removed in #127

- .azure/pipelines.yml
- CONTRIBUTING.md
- js/package.json
- nbcelltests/_version.py
1. Change azure feed name from `python-packages` to `packages-testing` (#67) to denote that (a) it's not only for python packages (named it before I knew what I was clicking in azure...) and (b) it's for test packages (official releases are on pypi/npm). See also https://github.com/timkpaine/jupyterlab_autoversion/pull/24. If both that PR and this PR are merged, we should probably just delete https://dev.azure.com/tpaine154/jupyter/_packaging?_a=feed&feed=python-packages (shouldn't matter as it's only a test channel; the packages are on pypi/npm).
2. In #133 I manually modified the version in `.bumpversion.cfg`, forgetting that the same info is also stored in `nbcelltests/_version.py` and `js/package.json` - so fix up those two versions also.
3. Formatting fix in CONTRIBUTING.
> More release fixups

- .bumpversion.cfg
- js/package.json
- nbcelltests/_version.py
Release 0.2.0a1. Should be the last pre-release - everything seems ok now.
P. S. A downside with this workflow is the releaser needs to get these kinds of trivial commits reviewed. If I attempt to push to jpmorganchase/nbcelltests' master:
```
$ git push upstream master
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 12 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 599 bytes | 599.00 KiB/s, done.
Total 7 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 4 of 4 required status checks have not succeeded: 3 expected. At least 1 approving review is required by reviewers with …
```
> Bump version: (0, 2, 0, 'alpha', 0) → 0, 2, 0, 'alpha', 1

- .azure/pipelines.yml
- .azure/test-template.yml
- CONTRIBUTING.md
- README.md
- setup.py
* Fix lab extension "speculative installation"
* Add tests of "user installation" (i.e. pip install the packages that were uploaded to azure artifacts, then run the package tests and check the extensions are active).
To do:
> Fix lab extension bundling and speculative installation

- nbcelltests/lint.py
We recently removed "lines_per_cell", "cells_per_notebook", "function_definitions", and "class_definitions" as concepts from nbcelltests.test. At the same time, we meant to remove coverage as a concept from nbcelltests.lint, but somehow forgot to actually do it.
See #109
> Remove coverage from lint checks.

- nbcelltests/lint.py
- nbcelltests/tests/test_lint.py
> Make lint.runWithHTMLReturn() respect supplied rules

- nbcelltests/lint.py
- nbcelltests/shared.py
- nbcelltests/tests/_lint_disable.ipynb
- nbcelltests/tests/more.ipynb
- nbcelltests/tests/test_lint.py
- nbcelltests/tests/test_shared.py
One way of doing #141 
~~Note: base branch should be updated to master once #144 is merged (i.e. this depends on #144).~~
I'm not sure I like disabling rules such as number of cells per notebook via a comment in a code cell, but this might allow someone to integrate with a pre-existing system that already uses such comments for python code.
For instance, if you already had a system that allowed for disabling lint rules in python code e.g. via a `# STATIC_CHECK_DISABLE rulename` comment, and that system counted such comments as part of a static check score, and your notebooks were already going through such a system, then this might help you.
The `# STATIC_CHECK_DISABLE` part is just a regex, so can be anything.
Example use: 
* the system currently does `nbcelltests.lint.run(notebook, …
> Support disabling of one or more celltests lint rules via comment in code cell

- .azure/test-template.yml
- CONTRIBUTING.md
- README.md
Needed to install test deps before testing installed package.
Note that pip installing the 0.2.0a2 package (plus doing a jupyter lab build) does result in extensions being successfully active (I ran the changes here in isolation to check):
Also: 
* Fixed link to npm package (jupyterlab_celltests, not nbcelltests).
* Added clarification to release procedure. Mainly that the procedure described has package building and testing occur on neutral CI machines across multiple platforms, and is best viewed as a somewhat asynchronous process, during which you'll likely want to be working on other things :) But if you want to iterate faster, you can of course still use local commands and environments to build and test packages.
> Fix testing of "user installation testing"

- js/package.json
Fixes #159 (see comments there)
Tried locally on linux:
```
$ npm publish --dry-run
> jupyterlab_celltests@0.2.0 prepublishOnly .
> cpx ../README.md . && cpx ../LICENSE . && npm run build
> jupyterlab_celltests@0.2.0 build /home/sefkw/code/jpmorganchase/nbcelltests/js
> tsc
npm notice 
npm notice 📦  jupyterlab_celltests@0.2.0
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE          
npm notice 1.5kB  style/index.css  
npm notice 1.4kB  lib/activate.js  
npm notice 840B   lib/index.js     
npm notice 4.5kB  lib/run.js       
npm notice 1.9kB  lib/tool.js      
npm notice 1.1kB  lib/utils.js     
npm notice 13.2kB lib/widget.js    
npm notice 2.4kB  package.json     
npm notice 7.0kB  README.md        
npm notice 717B   lib/activate.d.ts
npm notice 545B   lib/index.d.ts …
```
> Copy license and readme into npm package.

- js/package.json
- nbcelltests/shared.py
- nbcelltests/test.py
- nbcelltests/tests/test_test.py
- nbcelltests/tests_vendored.py
- setup.py
Rather than "dumping the source code from the notebook as a string into the generated test script string", the generated test script now reads the source code from the notebook when the test script is *run*. This means the generated test script will no longer become out of sync with the notebook.
However, that is not the primary motivation of this PR :) The primary motivation is to move celltest assembly out of a "gradually built up string" and into real source code.
It would be possible to decouple the two changes above, but it was easier to do them together. I would be ok with separating, though, if we agree on a way to storing the notebook's source code in a python script in a way it can be submitted to the kernel.
Notes:
* We are not at the desired end state yet; apart from getting …
> Get notebook source at run time; don't store notebook code in generated script.

- js/src/widget.ts
- nbcelltests/shared.py
- nbcelltests/tests/_broken_magics.ipynb
- nbcelltests/tests/_cell_counting.ipynb
- nbcelltests/tests/_cell_not_injected_or_mocked.ipynb
- nbcelltests/tests/_cumulative_run.ipynb
- nbcelltests/tests/_empty_cell_with_test.ipynb
- nbcelltests/tests/_emptyast_cell_with_test.ipynb
- nbcelltests/tests/_skips.ipynb
- nbcelltests/tests/test_shared.py
- nbcelltests/tests/test_test.py
- nbcelltests/tests_vendored.py
Fixes #169, i.e. implements what is described in the opening comment there.
The important changes are in nbcelltets.tests_vendored - the rest is test updates.
Questions:
* Decide what magic comment to use for saying "cell is mocked" (i.e. do not run this cell). Currently `# no %cell`. Vidar proposed `# nbcelltest-skip`. Or even possibly go straight to #171? (I'd rather try the current underlying behavior out for a bit, then if we are keeping it, use a better mechanism than comment.)
* Agree it's ok to generate and run a `test_cell_3` method (as opposed to not generating/skipping) when no explicit test has been supplied for cell 3, and hence the test defaults to `%cell`. (This is "case 3 from #169.) I think we need some people to try it out in lab etc and give feedback one way or the …
> Celltest always generated for non-empty code cell, and always runs; defaults to %cell if test is empty

- .azure/pipelines.yml
- .bumpversion.cfg
- js/package.json
- nbcelltests/_version.py
Whatever older version of pip is part of azure's python distribution does include pyproject.toml in sdist.
> Upgrade pip before building packages.

- .azure/dev-template.yml
- nbcelltests/extension.py
- nbcelltests/lint.py
- nbcelltests/shared.py
- nbcelltests/tests/test_test.py
- pyproject.toml
- setup.py
* Allow someone to use nbcelltests.lint on python 2.
* Enable installation without manual modification on python 2.
* Add python 2 to CI matrix (but don't run all parts of CI with python 2).
> Support nbcelltests.lint on python 2

- nbcelltests/lint/__init__.py
Also, use python exporter, since we are in a block called 'run_python_linter' (but see comments in #202).
Fixes #202
> Exclude raw cells when converting notebook to .py file for python code linting

- .azure/dev-template.yml
- Makefile
- nbcelltests/tests/test_test.py
- setup.py
Resolves #107:
- `pytest-xdist` will now be installed on Windows
- Replaced `--forked` with `-n 2`
- Tests like `test_basic_runWithReturn_pass` and 4 others do not want to have the file `__cell_coverage_test.py` already created. I grouped all these 5 tests under a class `TestCoverage` so that these tests are run sequentially by a worker spawn by `pytest-xdist`
- Removed special handling of `--forked`. Now, tests like `test_state` behave as if it's always `FORKED=False`.
Naming Choices:
- Would you want to rename `make pytest-forked` to something else?
- Azure test `pytest --forked` renames to `pytest -n 2`
- Is the class name `TestCoverage` apt for grouping these tests? `test_basic_runWithReturn_pass`, `test_basic_runWithReturn_fail`, `test_basic_runWithReport_pass`, …
> Replaced --forked in internal tests
